version: '3.9'

services:
  rustapp:
    container_name: rustapp
    image: fibrinlab/ctrl-health:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'

volumes:
  pgdata: {}